name: flutter_application
description: "Politics App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  package_info_plus: ^8.3.0
  settings_ui: ^2.0.2
  supabase: ^2.8.0
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - .env
